### ISSUE TITLE
Update repo to current version

### ISSUE THREAD

**Issue by srchulo** [frioux/Catalyst-Plugin-Session-Store-DBIC#1]
Hi,

Could this repo be updated to the current version that's on CPAN?? I've filed a bug here:

https://rt.cpan.org/Ticket/Display.html?id=112679#txn-1672955

And I'd love to submit a pull request to fix it.

Thanks!

**Comment by frioux** [comment]
I am not actually one of the maintainers, and I am pretty sure I made this repo just to convert from SVN for the original authors.  Maybe email BOBTFISH@cpan.org, DANIELTWC@cpan.org, FLORA@cpan.org, JHANNAH@cpan.org?

**Comment by srchulo** [comment]
Sounds good. Thanks for the reply!
